workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: "Package extension"
          command: bash release.sh
      - persist_to_workspace:
          root: ./
          paths:
            - package.zip

  publish:
    docker:
      - image: cibuilds/chrome-extension:latest
    environment:
      - APP_ID: ialfbkhnjhhgeplfephldjaofhggmkjn
    steps:
      - attach_workspace:
          at: /root/workspace
      - run:
          name: "Publish to the Google Chrome Store"
          command: |
            publish /root/workspace/package.zip
