workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - chrome-publish:
          requires:
            - build
          filters:
            branches:
              only: master
      - firefox-publish:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: "Package extension"
          command: bash scripts/package.sh
      - persist_to_workspace:
          root: ./
          paths:
            - package.zip

  chrome-publish:
    docker:
      - image: circleci/node:lts
    environment:
      - APP_ID: ialfbkhnjhhgeplfephldjaofhggmkjn
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish to the Google Chrome Store"
          command: bash scripts/chrome_publish.sh /tmp/workspace/package.zip

  firefox-publish:
    docker:
      - image: circleci/node:lts
    environment:
      - APP_ID: 47d88be1-99a8-4be7-9c17-e620adf4acbd
    steps:
      - checkout
      - run: npm install web-ext
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish to the Firefox Addon Store"
          command: bash scripts/firefox_publish.sh /tmp/workspace/package.zip
